### ISSUE TITLE
Create-React-App changed the order of loading env files

### ISSUE THREAD

**Issue by Favna** [djdmbrwsk/dotenv-cra#84]
Hi there,

While browsing through commits to the CRA repo since the release of 3.4.1 as I was curious if a commit of my own landed in 3.4.3 I noticed 1 commit that changed the order in which `.env` files are loaded: https://github.com/facebook/create-react-app/commit/26a1c7f6b38fe7119a8fd92d10eb63597376d7de (PR that belongs to commit: https://github.com/facebook/create-react-app/pull/9037)

From what I can tell from your README as well as commit history you are still using the order of loading env files prior to this commit. Can you change your loading to match CRA again?

Great lib btw! Really helpful!

**Comment by djdmbrwsk** [comment]
Hey @Favna 👋 Thanks for the heads-up! I'll make the change and publish a release.
